services:
  legacy-api:
    build:
      context: ./legacy-api
    container_name: legacy-api
    restart: always
    ports:
      - "4040:4040"

  recruitment-api:
    build:
      context: ./new-recruitment-api
    container_name: recruitment-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LEGACY_API_URL=http://legacy-api:4040
      - LEGACY_API_KEY=0194ec39-4437-7c7f-b720-7cd7b2c8d7f4
    depends_on:
      - legacy-api
    volumes:
      - recruitment-data:/app/data

volumes:
  recruitment-data: